"""empty message

Revision ID: 970c6dbdad8e
Revises: 536f1609caed
Create Date: 2021-08-18 11:54:10.251078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970c6dbdad8e'
down_revision = '536f1609caed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###
